name: test

on:
  push:
    branches:
      - main
     
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version
        id: semver-tagger
        uses: sanikolaev/semver-tagger-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conventional_commits_authors: conventional@example.com
          debug: true
          ignore_patterns: '\.md$|^test/|^manual/|\^.clt|\^.github|\^.patterns|\.txt$|\.yml$|\^.gitignore'
